In [11]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("travel.sqlite")
cur = conn.cursor()

In [12]:
import zipfile

with zipfile.ZipFile("travel.sqlite.zip", "r") as z:
    z.extractall()

In [13]:
query = "SELECT name FROM sqlite_master WHERE type='table'"
pd.read_sql(query, conn)

              name
0   aircrafts_data
1    airports_data
2  boarding_passes
3         bookings
4          flights
5            seats
6   ticket_flights
7          tickets

In [14]:
query = "SELECT * FROM aircrafts_data LIMIT 10;"
pd.read_sql(query, conn)

  aircraft_code                                              model  range
0           773    {"en": "Boeing 777-300", "ru": "Боинг 777-300"}  11100
1           763    {"en": "Boeing 767-300", "ru": "Боинг 767-300"}   7900
2           SU9  {"en": "Sukhoi Superjet-100", "ru": "Сухой Суп...   3000
3           320  {"en": "Airbus A320-200", "ru": "Аэробус A320-...   5700
4           321  {"en": "Airbus A321-200", "ru": "Аэробус A321-...   5600
5           319  {"en": "Airbus A319-100", "ru": "Аэробус A319-...   6700
6           733    {"en": "Boeing 737-300", "ru": "Боинг 737-300"}   4200
7           CN1  {"en": "Cessna 208 Caravan", "ru": "Сессна 208...   1200
8           CR2  {"en": "Bombardier CRJ-200", "ru": "Бомбардье ...   2700

In [15]:
query = "SELECT * FROM airports_data LIMIT 5;"
pd.read_sql(query, conn)

,airport_code,airport_name,city,coordinates,timezone
0,YKS,"{""en"": ""Yakutsk Airport"", ""ru"": ""Якутск""}","{""en"": ""Yakutsk"", ""ru"": ""Якутск""}","(129.77099609375,62.0932998657226562)",Asia/Yakutsk
1,MJZ,"{""en"": ""Mirny Airport"", ""ru"": ""Мирный""}","{""en"": ""Mirnyj"", ""ru"": ""Мирный""}","(114.03900146484375,62.534698486328125)",Asia/Yakutsk
2,KHV,"{""en"": ""Khabarovsk-Novy Airport"", ""ru"": ""Хабар...","{""en"": ""Khabarovsk"", ""ru"": ""Хабаровск""}","(135.18800354004,48.5279998779300001)",Asia/Vladivostok
3,PKC,"{""en"": ""Yelizovo Airport"", ""ru"": ""Елизово""}","{""en"": ""Petropavlovsk"", ""ru"": ""Петропавловск-К...","(158.453994750976562,53.1679000854492188)",Asia/Kamchatka
4,UUS,"{""en"": ""Yuzhno-Sakhalinsk Airport"", ""ru"": ""Хом...","{""en"": ""Yuzhno-Sakhalinsk"", ""ru"": ""Южно-Сахали...","(142.718002319335938,46.8886985778808594)",Asia/Sakhalin

In [16]:
query = "SELECT * FROM boarding_passes LIMIT 5;"
pd.read_sql(query, conn)

       ticket_no  flight_id  boarding_no seat_no
0  0005435212351      30625            1      2D
1  0005435212386      30625            2      3G
2  0005435212381      30625            3      4H
3  0005432211370      30625            4      5D
4  0005435212357      30625            5     11A

In [17]:
query = "SELECT * FROM bookings LIMIT 5;"
pd.read_sql(query, conn)

  book_ref               book_date  total_amount
0   00000F  2017-07-05 03:12:00+03        265700
1   000012  2017-07-14 09:02:00+03         37900
2   000068  2017-08-15 14:27:00+03         18100
3   000181  2017-08-10 13:28:00+03        131800
4   0002D8  2017-08-07 21:40:00+03         23600

In [18]:
query = "SELECT * FROM flights LIMIT 5;"
pd.read_sql(query, conn)

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N
1,3979,PG0052,2017-08-25 14:50:00+03,2017-08-25 17:35:00+03,VKO,HMA,Scheduled,CR2,\N,\N
2,4739,PG0561,2017-09-05 12:30:00+03,2017-09-05 14:15:00+03,VKO,AER,Scheduled,763,\N,\N
3,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N
4,6938,PG0461,2017-09-04 12:25:00+03,2017-09-04 13:20:00+03,SVO,ULV,Scheduled,SU9,\N,\N

In [19]:
query = "SELECT * FROM seats LIMIT 5;"
pd.read_sql(query, conn)

  aircraft_code seat_no fare_conditions
0           319      2A        Business
1           319      2C        Business
2           319      2D        Business
3           319      2F        Business
4           319      3A        Business

In [20]:
query = "SELECT * FROM ticket_flights LIMIT 5;"
pd.read_sql(query, conn)

       ticket_no  flight_id fare_conditions  amount
0  0005432159776      30625        Business   42100
1  0005435212351      30625        Business   42100
2  0005435212386      30625        Business   42100
3  0005435212381      30625        Business   42100
4  0005432211370      30625        Business   42100

In [21]:
query = "SELECT * FROM tickets LIMIT 5;"
pd.read_sql(query, conn)

       ticket_no book_ref passenger_id
0  0005432000987   06B046  8149 604011
1  0005432000988   06B046  8499 420203
2  0005432000989   E170C3  1011 752484
3  0005432000990   E170C3  4849 400049
4  0005432000991   F313DD  6615 976589

In [ ]:
# 1) Average ticket price for each fare condition

In [23]:
query = """
SELECT fare_conditions,
       ROUND(AVG(amount), 2) AS avg_price
FROM ticket_flights
GROUP BY fare_conditions
ORDER BY fare_conditions;
"""

pd.read_sql(query, conn)

  fare_conditions  avg_price
0        Business   51143.42
1         Comfort   32740.55
2         Economy   15959.81

In [ ]:
# 2) To find from which airport most delays occurred

In [ ]:
query = "SELECT DISTINCT status FROM flights;"
df = pd.read_sql(query, conn)
df

      status
0  Scheduled
1  Cancelled
2    Arrived
3    On Time
4    Delayed
5   Departed

In [26]:
query = """
SELECT departure_airport,
       SUM(CASE WHEN status = 'Delayed' THEN 1 ELSE 0 END) AS n_delays
FROM flights
GROUP BY departure_airport
ORDER BY n_delays DESC LIMIT 10;
"""

pd.read_sql(query, conn)

  departure_airport  n_delays
0               SVO         6
1               DME         6
2               LED         3
3               KZN         2
4               KUF         2
5               YKS         1
6               VKT         1
7               VKO         1
8               ULV         1
9               TBW         1

In [27]:
query = """
SELECT *
FROM flights
JOIN airports_data
    ON flights.departure_airport = airports_data.airport_code
WHERE flights.departure_airport = 'SVO' LIMIT 1;
"""

pd.read_sql(query, conn)

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival,airport_code,airport_name,city,coordinates,timezone
0,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N,SVO,"{""en"": ""Sheremetyevo International Airport"", ""...","{""en"": ""Moscow"", ""ru"": ""Москва""}","(37.4146000000000001,55.9725990000000024)",Europe/Moscow

In [28]:
query = """
SELECT *
FROM flights
JOIN airports_data
    ON flights.departure_airport = airports_data.airport_code
WHERE flights.departure_airport = 'DME' LIMIT 1;
"""

pd.read_sql(query, conn)

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival,airport_code,airport_name,city,coordinates,timezone
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N,DME,"{""en"": ""Domodedovo International Airport"", ""ru...","{""en"": ""Moscow"", ""ru"": ""Москва""}","(37.9062995910644531,55.4087982177734375)",Europe/Moscow

In [ ]:
# This means that among app airports the two in Moscow, Russia 
# "Sheremetyevo International Airport" and "Domodedovo International Airport" recorded the highest number of delays

In [ ]:
# 3) The least popular destinations (airports with the lowest number of arrivals)

In [31]:
query = """
SELECT arrival_airport,
       COUNT(flight_id) AS n_flights
FROM flights
GROUP BY arrival_airport
ORDER BY n_flights ASC LIMIT 10;
"""

pd.read_sql(query, conn)

  arrival_airport  n_flights
0             KXK         17
1             USK         18
2             NYA         26
3             PKC         26
4             PYJ         27
5             DYR         34
6             GDX         35
7             IWA         36
8             KYZ         44
9             LPK         44

In [32]:
query = """
SELECT departure_airport,
       COUNT(flight_id) AS n_flights
FROM flights
GROUP BY departure_airport
ORDER BY n_flights DESC LIMIT 10;
"""

pd.read_sql(query, conn)

  departure_airport  n_flights
0               DME       3217
1               SVO       2981
2               LED       1900
3               VKO       1719
4               OVB       1055
5               KJA        707
6               SVX        689
7               PEE        619
8               ROV        617
9               BZK        610

In [ ]:
# This means, that although delays were recorded at the two airports mentioned above,   
# they  also handle the majority of flights, which may expain the dalays

In [ ]:
# 4) Join tables to see which passenger bought their tichet earliest

In [35]:
big_data = """
SELECT *
FROM bookings
JOIN tickets
    ON bookings.book_ref = tickets.book_ref
JOIN ticket_flights
    ON tickets.ticket_no = ticket_flights.ticket_no
JOIN flights
    ON ticket_flights.flight_id = flights.flight_id LIMIT 10;
"""

pd.read_sql(big_data, conn)

,book_ref,book_date,total_amount,ticket_no,book_ref,passenger_id,ticket_no,flight_id,fare_conditions,amount,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,00000F,2017-07-05 03:12:00+03,265700,0005435838975,00000F,1708 262537,0005435838975,5995,Economy,66400,5995,PG0703,2017-07-16 17:15:00+03,2017-07-17 02:00:00+03,SVO,UUS,Arrived,319,2017-07-16 17:19:00+03,2017-07-17 01:57:00+03
1,00000F,2017-07-05 03:12:00+03,265700,0005435838975,00000F,1708 262537,0005435838975,18058,Business,199300,18058,PG0704,2017-07-24 10:45:00+03,2017-07-24 19:30:00+03,UUS,SVO,Arrived,319,2017-07-24 10:47:00+03,2017-07-24 19:26:00+03
2,000012,2017-07-14 09:02:00+03,37900,0005432527326,000012,9091 269355,0005432527326,7737,Economy,14000,7737,PG0224,2017-07-28 17:05:00+03,2017-07-28 18:50:00+03,SVO,AER,Arrived,773,2017-07-28 17:08:00+03,2017-07-28 18:54:00+03
3,000012,2017-07-14 09:02:00+03,37900,0005432527326,000012,9091 269355,0005432527326,30620,Comfort,23900,30620,PG0013,2017-08-09 18:15:00+03,2017-08-09 20:00:00+03,AER,SVO,Arrived,773,2017-08-09 18:17:00+03,2017-08-09 20:03:00+03
4,000068,2017-08-15 14:27:00+03,18100,0005432293273,000068,5895 674437,0005432293273,1039,Economy,10200,1039,PG0517,2017-08-28 10:30:00+03,2017-08-28 11:50:00+03,DME,SCW,Scheduled,763,\N,\N
5,000068,2017-08-15 14:27:00+03,18100,0005432293273,000068,5895 674437,0005432293273,17082,Economy,7900,17082,PG0570,2017-08-28 14:05:00+03,2017-08-28 15:10:00+03,SCW,SVX,Scheduled,733,\N,\N
6,000181,2017-08-10 13:28:00+03,131800,0005435545944,000181,6799 285573,0005435545944,1039,Economy,10200,1039,PG0517,2017-08-28 10:30:00+03,2017-08-28 11:50:00+03,DME,SCW,Scheduled,763,\N,\N
7,000181,2017-08-10 13:28:00+03,131800,0005435545944,000181,6799 285573,0005435545944,11238,Economy,19100,11238,PG0378,2017-09-07 11:40:00+03,2017-09-07 14:15:00+03,SVX,NSK,Scheduled,SU9,\N,\N
8,000181,2017-08-10 13:28:00+03,131800,0005435545944,000181,6799 285573,0005435545944,17082,Economy,7900,17082,PG0570,2017-08-28 14:05:00+03,2017-08-28 15:10:00+03,SCW,SVX,Scheduled,733,\N,\N
9,000181,2017-08-10 13:28:00+03,131800,0005435545944,000181,6799 285573,0005435545944,20881,Economy,28700,20881,PG0125,2017-09-08 14:45:00+03,2017-09-08 18:35:00+03,NSK,DME,Scheduled,SU9,\N,\N

In [36]:
changed_data = """
SELECT *,
SUBSTR(book_date, 1, 10) AS book_day
SUBSTR(scheduled_departure, 1, 10) AS scheduled_day
FROM big_data;
"""
changed_data

'\nSELECT *,\nSUBSTR(book_date, 1, 10) AS book_day\nSUBSTR(scheduled_departure, 1, 10) AS scheduled_day\nFROM big_data;\n'

In [ ]:
# Unfortunately, the dates are strings, so calculating the difference, but this part didn't work

In [ ]:
# 5) Aircraft model which the highest number of flights

In [39]:
query = """
SELECT flights.aircraft_code,
       aircrafts_data.model AS aircraft_model,
       COUNT(flights.flight_id) AS n_flights
FROM flights
JOIN aircrafts_data
    ON flights.aircraft_code = aircrafts_data.aircraft_code
GROUP BY flights.aircraft_code, aircrafts_data.model
ORDER BY n_flights ASC
LIMIT 10;
"""

pd.read_sql(query, conn)

  aircraft_code                                     aircraft_model  n_flights
0           773    {"en": "Boeing 777-300", "ru": "Боинг 777-300"}        610
1           763    {"en": "Boeing 767-300", "ru": "Боинг 767-300"}       1221
2           319  {"en": "Airbus A319-100", "ru": "Аэробус A319-...       1239
3           733    {"en": "Boeing 737-300", "ru": "Боинг 737-300"}       1274
4           321  {"en": "Airbus A321-200", "ru": "Аэробус A321-...       1952
5           SU9  {"en": "Sukhoi Superjet-100", "ru": "Сухой Суп...       8504
6           CR2  {"en": "Bombardier CRJ-200", "ru": "Бомбардье ...       9048
7           CN1  {"en": "Cessna 208 Caravan", "ru": "Сессна 208...       9273

In [ ]:
# The results show that the CN1 and CR2 aircraft carry the most flights, making them the most popular

In [ ]:
# 6) Finding the  top 10 most loyal customers

In [42]:
query = """
SELECT passenger_id,
       COUNT(ticket_no) AS n_tickets
FROM tickets
GROUP BY passenger_id
ORDER BY n_tickets DESC LIMIT 10;
"""

pd.read_sql(query, conn)

  passenger_id  n_tickets
0  9999 979738          1
1  9999 939010          1
2  9999 935084          1
3  9999 913541          1
4  9999 898268          1
5  9999 894116          1
6  9999 893789          1
7  9999 891617          1
8  9999 886031          1
9  9999 872539          1

In [ ]:
# The result suggests either we have no loyal customers (unlikely),
# or the data covers a short period where even loyal customers took only one flight

In [ ]:
# 7) aircrafts generating the highest revenue

In [45]:
query = """
SELECT flights.aircraft_code,
       aircrafts_data.model AS aircraft_model,
       SUM(ticket_flights.amount) AS total_revenue
FROM flights
JOIN ticket_flights
    ON flights.flight_id = ticket_flights.flight_id
JOIN aircrafts_data
    ON flights.aircraft_code = aircrafts_data.aircraft_code
GROUP BY flights.aircraft_code, aircrafts_data.model
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

,aircraft_code,aircraft_model,total_revenue
0,SU9,"{""en"": ""Sukhoi Superjet-100"", ""ru"": ""Сухой Суп...",5114484700
1,763,"{""en"": ""Boeing 767-300"", ""ru"": ""Боинг 767-300""}",4371277100
2,773,"{""en"": ""Boeing 777-300"", ""ru"": ""Боинг 777-300""}",3431205500
3,319,"{""en"": ""Airbus A319-100"", ""ru"": ""Аэробус A319-...",2706163100
4,CR2,"{""en"": ""Bombardier CRJ-200"", ""ru"": ""Бомбардье ...",1982760500
5,321,"{""en"": ""Airbus A321-200"", ""ru"": ""Аэробус A321-...",1638164100
6,733,"{""en"": ""Boeing 737-300"", ""ru"": ""Боинг 737-300""}",1426552100
7,CN1,"{""en"": ""Cessna 208 Caravan"", ""ru"": ""Сессна 208...",96373800

In [ ]:
# As we can see, the SU9 is the highest revenue-generating aircraft for our customers.

In [ ]:
# Finally, I would like to determine the proportion of flights that were business class for each aircraft.

In [48]:
query = """
SELECT flights.aircraft_code,
       aircrafts_data.model AS aircraft_model,
       SUM(CASE WHEN ticket_flights.fare_conditions = 'Business' THEN 1 ELSE 0 END) * 1.0 / COUNT(ticket_flights.ticket_no) AS business_rate
FROM flights
JOIN ticket_flights
    ON flights.flight_id = ticket_flights.flight_id
JOIN aircrafts_data
    ON flights.aircraft_code = aircrafts_data.aircraft_code
GROUP BY flights.aircraft_code, aircrafts_data.model
ORDER BY business_rate DESC;
"""

pd.read_sql(query, conn)

,aircraft_code,aircraft_model,business_rate
0,319,"{""en"": ""Airbus A319-100"", ""ru"": ""Аэробус A319-...",0.171324
1,321,"{""en"": ""Airbus A321-200"", ""ru"": ""Аэробус A321-...",0.164036
2,763,"{""en"": ""Boeing 767-300"", ""ru"": ""Боинг 767-300""}",0.134651
3,SU9,"{""en"": ""Sukhoi Superjet-100"", ""ru"": ""Сухой Суп...",0.124187
4,733,"{""en"": ""Boeing 737-300"", ""ru"": ""Боинг 737-300""}",0.092646
5,773,"{""en"": ""Boeing 777-300"", ""ru"": ""Боинг 777-300""}",0.074950
6,CN1,"{""en"": ""Cessna 208 Caravan"", ""ru"": ""Сессна 208...",0.000000
7,CR2,"{""en"": ""Bombardier CRJ-200"", ""ru"": ""Бомбардье ...",0.000000

In [ ]:
# The chart is very interesting. My hypothesis was that SU9 leads in revenue generation
# because most of its tickets are business class. However, there are three aircraft with a higher proportion of business class passengers,
# yet these aircraft lag behind in revenue compared to the top three.